language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - lsb_release -a
  - pecl install install ssh2-1.1.2
  - echo "extension=ssh2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: php -m | grep ssh2
