language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - lsb_release -a
  - sudo apt-get update && sudo apt-get install libssh2-1 -y
  - echo "extension=ssh2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: php -m | grep ssh2
